### ISSUE TITLE
[Feature request] Multiple channels assigned to specific locations

### ISSUE THREAD

**Issue by kamieniarz** [5310/discord-bot-castform#10]
So basically if I have multiple cities I'd like weather to be sent to the channel of that city - currently it's not possible and I'd have to run multiple instances :/ Would that be possible? Maybe webhook support?

**Comment by 5310** [comment]
Webhook support might be pretty nice actually. I never considered it before, but what with our own server being so fickle at staying up, a shared local server might be the way to go, which would be best served with a hook.

I'll have to look into it... :thinking:

**Comment by 5310** [comment]
Added webhook support in branch `v2-webhook`. [Readme file](https://github.com/5310/discord-bot-castform/blob/v2-webhook/README.md) explains current config.
