### ISSUE TITLE
Formatting Broken on Discord Desktop

### ISSUE THREAD

**Issue by ajstewart** [5310/discord-bot-castform#5]
In case anyone comes looking, something has changed such that the formatting on the desktop/browser version of Discord is currently broken (see below).

Mobile (at least on iOS) still displays correctly.

<img width="911" alt="Screen Shot 2019-08-31 at 10 44 06 am" src="https://user-images.githubusercontent.com/3306161/64062307-23a0a700-cc28-11e9-9f1c-367fa6010861.png">

**Comment by ajstewart** [comment]
As of 01/09 11:30 AEST the formatting has fixed itself.

**Comment by 5310** [comment]
I was worried because even after reverting the test changes I made yesterday the forecasts were coming up broken. Then I remembered Discord had Service Workers now. Refreshed, working again! :raised_hands:
